name: Red Uno (Cochabamba)

on:
  schedule:
    - cron: '0 4,16 * * *'
  
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

       
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "Update"
      
      
      - name: grab m3u files
        run: |
          pwd
          cd ./core/platforms/
<<<<<<< HEAD
<<<<<<< HEAD
          python3 dailymotion.py "x827j2y" > ../../streams/Red_Uno_Cochabamba.m3u8
          echo "m3u grabbed"
=======
          python3 dailymotion.py "x8ob23p" > ../../streams/Red_Uno_Cochabamba.m3u8
>>>>>>> 80bb73864 (removing useless comments)
=======
          python3 dailymotion.py "x8ra7t7" > ../../streams/Red_Uno_Cochabamba.m3u8
>>>>>>> edd2f5eba (changing red uno links - fixes #97)
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "Red Uno (Cochabamba) updated"
          git push
